
version: '3.7'

services:
  broker1:
    image: netifi/broker:1.6.2
    restart: always
    networks:
      - netifi
    environment:
      BROKER_SERVER_OPTS: >
        '-Dnetifi.broker.console.enabled=true'
        '-Dnetifi.broker.ssl.disabled=true'
        '-Dnetifi.authentication.0.accessKey=9007199254740991'
        '-Dnetifi.authentication.0.accessToken=kTBDVtfRBO4tHOnZzSyY5ym2kfY='
        '-Dnetifi.broker.admin.accessKey=9007199254740991'
        '-Dnetifi.broker.admin.accessToken=kTBDVtfRBO4tHOnZzSyY5ym2kfY='
    ports:
      - "7001:7001"
      - "8001:8001"
      - "8101:8101"
      - "9000:9000"
networks:
  netifi:
